apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
    }
    namespace 'pl.pzienowicz.autoscrollviewpager'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}