apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'


android {
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 33

        consumerProguardFiles 'proguard-rules.pro'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation "androidx.annotation:annotation:1.5.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.10"
}