plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-android'
    id 'kotlin-kapt'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}

android {
    namespace 'ninja.cricks'
    compileSdk 33
    buildToolsVersion '33.0.0'

    defaultConfig {
        applicationId "ninja.cricks"
        minSdk 23
        targetSdk 33
        versionCode 4006
        versionName "4.4"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true
        setProperty("archivesBaseName", "Ninja11-$versionName")
    }

    buildFeatures {
        dataBinding true
    }

    buildTypes {
        debug {
            buildConfigField "boolean", "MLOG", "true"
            debuggable true
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        release {
            buildConfigField "boolean", "MLOG", "false"
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    lint {
        baseline = file("lint-baseline.xml")
    }
}

dependencies {

    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.5.3'
    implementation 'androidx.navigation:navigation-ui-ktx:2.5.3'
    implementation 'androidx.palette:palette-ktx:1.0.0'
    implementation 'androidx.browser:browser:1.5.0'
    implementation 'androidx.emoji:emoji:1.1.0'


    implementation 'com.google.android.material:material:1.8.0'
    implementation 'com.google.android.gms:play-services-auth:20.5.0'

    // firebase dependencies
    implementation platform('com.google.firebase:firebase-bom:30.5.0')
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-crashlytics-ktx'
    implementation 'com.google.firebase:firebase-messaging-ktx'
    implementation 'com.google.firebase:firebase-core'

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    implementation 'com.mikhaellopez:circularimageview:4.3.0'
    implementation 'com.intuit.sdp:sdp-android:1.0.6'
    implementation 'com.github.bumptech.glide:glide:4.13.2'

    implementation 'io.branch.sdk.android:library:5.0.4'

    implementation 'com.github.dhaval2404:imagepicker:1.8'

    // paytm all in one sdk
    implementation 'com.paytm.appinvokesdk:appinvokesdk:1.6.11'

    implementation 'com.github.mukeshsolanki:android-otpview-pinview:2.1.2'

    //room database
    implementation("androidx.room:room-runtime:2.5.1")
    annotationProcessor("androidx.room:room-compiler:2.5.1")
    // To use Kotlin annotation processing tool (kapt)
    kapt("androidx.room:room-compiler:2.5.1")
    //Kotlin Extensions and Coroutines support for Room
    implementation("androidx.room:room-ktx:2.5.1")

    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'

    // view pager for player stats
    implementation project(path: ':ultraviewpager')
    // flash bar
    implementation project(path: ':flashbar')

    // auto scroll view pager
    implementation project(path: ':autoscrollviewpager')

    // Header list view
    implementation 'com.github.IntruderShanky:Sectioned-RecyclerView:2.1.1'
    // phonepe payment gateway integration
    implementation 'phonepe.intentsdk.android.release:IntentSDK:2.3.0'

}